import type { Lead } from '@/types/lead'

export const MOCK_USER = {
  name: 'Lucas Mendes',
  email: 'lucas@pipeflow.app',
  initials: 'LM',
}

export const MOCK_WORKSPACES = [
  { id: '1', name: 'Agência Nova Era', initials: 'AN', plan: 'pro' as const },
  { id: '2', name: 'Consultoria Leite & Co', initials: 'CL', plan: 'free' as const },
  { id: '3', name: 'Freelance Pessoal', initials: 'FP', plan: 'free' as const },
]

export const MOCK_ACTIVE_WORKSPACE_ID = '1'

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    name: 'Ana Claudia Ferreira',
    email: 'ana.ferreira@ferreiraadv.com.br',
    phone: '(11) 98765-4321',
    company: 'Ferreira Advocacia',
    role: 'Sócia',
    status: 'qualificado',
    owner: 'Lucas Mendes',
    createdAt: '2026-03-10',
    activities: [
      { id: 'a1-1', leadId: '1', type: 'ligacao', description: 'Primeiro contato. Demonstrou interesse nos planos Pro.', createdAt: '2026-03-11T10:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a1-2', leadId: '1', type: 'email', description: 'Enviado material de apresentação e proposta comercial.', createdAt: '2026-03-12T14:30:00', createdBy: 'Lucas Mendes' },
      { id: 'a1-3', leadId: '1', type: 'reuniao', description: 'Reunião de alinhamento sobre funcionalidades necessárias para o escritório.', createdAt: '2026-03-15T09:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '2',
    name: 'Marcos Aurelio Oliveira',
    email: 'm.oliveira@grupooliveira.com.br',
    phone: '(21) 97654-3210',
    company: 'Grupo Oliveira Imóveis',
    role: 'Diretor Comercial',
    status: 'proposta',
    owner: 'Lucas Mendes',
    createdAt: '2026-03-08',
    activities: [
      { id: 'a2-1', leadId: '2', type: 'ligacao', description: 'Retornou contato após evento de networking.', createdAt: '2026-03-09T15:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a2-2', leadId: '2', type: 'reuniao', description: 'Apresentação do produto para a equipe comercial. Boa receptividade.', createdAt: '2026-03-13T11:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a2-3', leadId: '2', type: 'email', description: 'Proposta formal enviada com preço customizado para 8 usuários.', createdAt: '2026-03-18T16:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '3',
    name: 'Patricia Souza',
    email: 'patricia@souzaconsultoria.com.br',
    phone: '(31) 96543-2109',
    company: 'Souza & Irmãos Consultoria',
    role: 'Gerente',
    status: 'negociacao',
    owner: 'Lucas Mendes',
    createdAt: '2026-02-28',
    activities: [
      { id: 'a3-1', leadId: '3', type: 'email', description: 'Solicitou demonstração do painel de leads e pipeline.', createdAt: '2026-03-01T09:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a3-2', leadId: '3', type: 'reuniao', description: 'Demo ao vivo realizada. Pediu desconto para time de 10 usuários.', createdAt: '2026-03-05T14:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a3-3', leadId: '3', type: 'ligacao', description: 'Negociando valores. Aguardando aprovação da diretoria.', createdAt: '2026-03-20T10:30:00', createdBy: 'Lucas Mendes' },
      { id: 'a3-4', leadId: '3', type: 'nota', description: 'Decisão prevista para início de abril. Manter contato quinzenal.', createdAt: '2026-03-22T08:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '4',
    name: 'Roberto Cardoso',
    email: 'roberto@techsolutionsbr.com.br',
    phone: '(11) 95432-1098',
    company: 'Tech Solutions Brasil',
    role: 'CEO',
    status: 'ganho',
    owner: 'Lucas Mendes',
    createdAt: '2026-02-15',
    activities: [
      { id: 'a4-1', leadId: '4', type: 'ligacao', description: 'Primeiro contato via indicação da Ana Ferreira.', createdAt: '2026-02-16T10:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a4-2', leadId: '4', type: 'reuniao', description: 'Apresentação completa. Interesse imediato no plano Pro anual.', createdAt: '2026-02-20T14:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a4-3', leadId: '4', type: 'email', description: 'Contrato assinado. Boas-vindas ao PipeFlow!', createdAt: '2026-02-25T09:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '5',
    name: 'Fernanda Lima',
    email: 'fernanda@limaarquitetura.com.br',
    phone: '(41) 94321-0987',
    company: 'Lima Arquitetura e Design',
    role: 'Arquiteta',
    status: 'novo',
    owner: 'Lucas Mendes',
    createdAt: '2026-04-01',
    activities: [],
  },
  {
    id: '6',
    name: 'Diego Alves',
    email: 'diego.alves@alvesconstrutora.com.br',
    phone: '(85) 93210-9876',
    company: 'Alves Construtora',
    role: 'Engenheiro',
    status: 'contato',
    owner: 'Lucas Mendes',
    createdAt: '2026-03-25',
    activities: [
      { id: 'a6-1', leadId: '6', type: 'email', description: 'Respondeu ao formulário de contato do site. Quer entender sobre o módulo de pipeline.', createdAt: '2026-03-26T08:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '7',
    name: 'Camila Rocha',
    email: 'camila@rochaEventos.com.br',
    phone: '(71) 92109-8765',
    company: 'Rocha Eventos',
    role: 'Produtora',
    status: 'qualificado',
    owner: 'Lucas Mendes',
    createdAt: '2026-03-18',
    activities: [
      { id: 'a7-1', leadId: '7', type: 'ligacao', description: 'Ligação de qualificação. BANT confirmado — budget, autoridade e prazo definidos.', createdAt: '2026-03-19T11:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a7-2', leadId: '7', type: 'nota', description: 'Alto potencial. Empresa cresceu 30% no último ano. Agendar demo para a próxima semana.', createdAt: '2026-03-20T16:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '8',
    name: 'Thiago Nascimento',
    email: 'thiago@nascimentologistica.com.br',
    phone: '(62) 91098-7654',
    company: 'Nascimento Logística',
    role: 'Gerente de Operações',
    status: 'perdido',
    owner: 'Lucas Mendes',
    createdAt: '2026-02-10',
    activities: [
      { id: 'a8-1', leadId: '8', type: 'reuniao', description: 'Demo realizada. Sem budget aprovado para este semestre.', createdAt: '2026-02-15T10:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a8-2', leadId: '8', type: 'nota', description: 'Revisitar no Q4 2026. Orçamento previsto para outubro.', createdAt: '2026-02-16T09:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '9',
    name: 'Juliana Costa',
    email: 'ju.costa@costadigital.com.br',
    phone: '(51) 90987-6543',
    company: 'Costa Digital Marketing',
    role: 'Fundadora',
    status: 'novo',
    owner: 'Lucas Mendes',
    createdAt: '2026-04-10',
    activities: [],
  },
  {
    id: '10',
    name: 'Eduardo Martins',
    email: 'e.martins@martinsindustria.com.br',
    phone: '(11) 99876-5432',
    company: 'Martins Indústria',
    role: 'Diretor de Compras',
    status: 'proposta',
    owner: 'Lucas Mendes',
    createdAt: '2026-03-22',
    activities: [
      { id: 'a10-1', leadId: '10', type: 'ligacao', description: 'Avaliando solução para substituir planilhas de controle de fornecedores.', createdAt: '2026-03-23T14:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a10-2', leadId: '10', type: 'email', description: 'Proposta enviada incluindo integração via API com ERP atual.', createdAt: '2026-03-28T10:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '11',
    name: 'Larissa Pereira',
    email: 'larissa@pereiraClinica.com.br',
    phone: '(21) 98765-1234',
    company: 'Pereira Clínica Médica',
    role: 'Administradora',
    status: 'contato',
    owner: 'Lucas Mendes',
    createdAt: '2026-04-05',
    activities: [
      { id: 'a11-1', leadId: '11', type: 'ligacao', description: 'Primeiro contato. Agendou demonstração para a próxima semana.', createdAt: '2026-04-06T15:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '12',
    name: 'Bruno Santos',
    email: 'bruno.s@santosdistribuidora.com.br',
    phone: '(11) 97654-3210',
    company: 'Santos Distribuidora',
    role: 'Gerente de Vendas',
    status: 'ganho',
    owner: 'Lucas Mendes',
    createdAt: '2026-02-05',
    activities: [
      { id: 'a12-1', leadId: '12', type: 'reuniao', description: 'Reunião de fechamento. Assinou plano Pro anual com desconto de indicação.', createdAt: '2026-02-20T10:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '13',
    name: 'Isabela Gonçalves',
    email: 'isabela@goncalvesturismo.com.br',
    phone: '(48) 96543-2109',
    company: 'Gonçalves Turismo',
    role: 'Coordenadora',
    status: 'qualificado',
    owner: 'Lucas Mendes',
    createdAt: '2026-03-30',
    activities: [
      { id: 'a13-1', leadId: '13', type: 'email', description: 'Pediu informações sobre integração com sistemas de reservas e CRM.', createdAt: '2026-04-01T09:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a13-2', leadId: '13', type: 'ligacao', description: 'Qualificação confirmada. Time de 5 pessoas com necessidade imediata.', createdAt: '2026-04-03T11:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '14',
    name: 'Raphael Barbosa',
    email: 'raphael@barbosatec.com.br',
    phone: '(83) 95432-1098',
    company: 'Barbosa Tecnologia',
    role: 'CTO',
    status: 'negociacao',
    owner: 'Lucas Mendes',
    createdAt: '2026-03-15',
    activities: [
      { id: 'a14-1', leadId: '14', type: 'reuniao', description: 'Reunião técnica aprofundada sobre integrações via API e webhooks.', createdAt: '2026-03-20T14:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a14-2', leadId: '14', type: 'nota', description: 'Exigiu SLA de 99,9% e dados hospedados no Brasil antes de fechar.', createdAt: '2026-03-22T09:00:00', createdBy: 'Lucas Mendes' },
      { id: 'a14-3', leadId: '14', type: 'ligacao', description: 'Negociando contrato bianual com desconto de 20%. Aguardando proposta revisada.', createdAt: '2026-04-10T16:00:00', createdBy: 'Lucas Mendes' },
    ],
  },
  {
    id: '15',
    name: 'Natalia Ribeiro',
    email: 'nat.ribeiro@ribeiroidiomas.com.br',
    phone: '(61) 94321-0987',
    company: 'Ribeiro Escola de Idiomas',
    role: 'Diretora',
    status: 'novo',
    owner: 'Lucas Mendes',
    createdAt: '2026-04-20',
    activities: [],
  },
]
